import {
    AlertTriangle,
    ArrowRight,
    Bookmark,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    Github,
    HelpCircle,
    ImageIcon,
    Laptop,
    Loader2,
    LogOut,
    MessageSquare,
    Moon,
    MoreVertical,
    Pizza,
    Plus,
    Search,
    Settings,
    Sparkles,
    SunMedium,
    Trash,
    Twitter,
    User,
    X,
  } from "lucide-react"
  
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    trash: Trash,
    post: FileText,
    page: File,
    media: ImageIcon,
    settings: Settings,
    billing: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    help: HelpCircle,
    pizza: Pizza,
    sun: SunMedium,
    moon: Moon,
    laptop: Laptop,
    gitHub: Github,
    google: Github,
    twitter: Twitter,
    check: Check,
    bookmark: Bookmark,
    logout: LogOut,
    search: Search,
    sparkles: Sparkles,
    message: MessageSquare,
  }
  